###
# This file configures the project "Piper" pipeline of your project.
# For a reference of the configuration concept and available options, please have a look into its documentation.
#
# The documentation for the most recent pipeline version can always be found at:
#    https://www.project-piper.io/
#
# This is a YAML-file. YAML is an indentation-sensitive file format. Please make sure to properly indent changes to it.
###



### General project setup
#general:
#  inferBuildTool: true

### Step-specific configuration
#steps:
#  mavenExecute:
#    dockerImage: devxci/mbtci:1.0.14

#  artifactPrepareVersion:
#    versioningType: cloud_noTag

### Stage-specific configuration
#stages:
#  'Confirm':
#    manualConfirmation: false

#  Integration:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

#  Release:
#    cfTargets:
#      - org: 'DEV'
#        space: 'dev'
#        apiEndpoint: 'https://api.cf.us10-001.hana.ondemand.com'
#        appName: 'abapp'
#        manifest: 'manifest.yml'
#        credentialsId: 'deploy-to-cf'

#Release:
#  cloudFoundryDeploy: true
#  cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
#  cfOrg: "DEV"
#  cfSpace: "dev"
#  cfAppName: "abapp"
#  cfCredentialsId: "deploy-to-cf"
#  tmsUpload: false


general:
  inferBuildTool: true

steps:
  mavenExecute:
    dockerImage: "devxci/mbtci:0.14"

stages:
  - name: "Init"
    manualConfirmation: false

  - name: "Release"
    cloudFoundryDeploy:
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "DEV"
      space: "dev"
      credentialsId: "deploy-to-cf"  # Este ID debe coincidir con el configurado en SAP CI & D

credentials:
  - alias: "github_credentials"
    credentialId: "whc"  # Referencia al webhook configurado

repositories:
  - name: "abapp"
    url: "https://github.com/neb6/abapp.git"
    branch: "master"